import {Restauration} from "./restauration.model";
export const restaurations : Restauration[] = [
    {   id : "1",
        nom_restaurant : "belle vue" ,
	    menu : "spaghetti" ,
	    fruits : "orange" ,
	    boissons : "fanta" ,
    },
    {   id : "2",
    nom_restaurant : "belle vue" ,
    menu : "couscous" ,
    fruits : "banane" ,
    boissons : "cocacola" ,
    },
    {   id : "3",
    nom_restaurant : "belle vue" ,
    menu : "spaghetti" ,
    fruits : "fraise" ,
    boissons : "apla" ,
    },
    {   id : "4",
        nom_restaurant : "belle vue" ,
	    menu : "spaghetti" ,
	    fruits : "orange" ,
	    boissons : "fanta" ,
    },
    {   id : "5",
        nom_restaurant : "belle vue" ,
	    menu : "salade" ,
	    fruits : "orange" ,
	    boissons : "fanta" ,
    },

];
export default restaurations;